restaurante_reservas/Controllers/ClientesController.cs
using restaurante_reservas.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace restaurante_reservas.Controllers
{
    public class ClientesController : Controller
    {
        restauranteEntities db = new restauranteEntities();
        // GET: Clientes
        public ActionResult AdminClientes()
        {
            
            List<sp_Seleccionar_Usuarios_Admin_Result> usuariosList = db.sp_Seleccionar_Usuarios_Admin().ToList();
            return View(usuariosList);
        }

        // GET: Clientes/Details/5
        public ActionResult Details(int id)
        {

            return View();
        }

        // GET: Clientes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Clientes/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Clientes/Edit/5
        public ActionResult Edit(int id)
        {
            List<Estados> estadoList = db.Estados.Where(x => x.categoria == "usuario").ToList();
            ViewBag.estadoList = new SelectList(estadoList, "id", "estado");

            List<Roles> rolesList = db.Roles.ToList();
            ViewBag.rolesList = new SelectList(rolesList, "idRol", "Rol");

            sp_Seleccionar_Usuarios_Admin_Result myUsuario = (from c in db.sp_Seleccionar_Usuarios_Admin() where id == c.id select c).First();
            return View(myUsuario);
        }

        // POST: Clientes/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                db.sp_Actualizar_Usuarios_Admin(id,collection["contrasena"],Convert.ToInt32(collection["id_Estado"]),Convert.ToInt32(collection["id_Rol"]));

                return RedirectToAction("AdminClientes");
            }
            catch(Exception ex)
            {
                ViewData["Error"] = "Ocurrio un error : " + ex.Message;
                return View();
            }
        }

        // GET: Clientes/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Clientes/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

restaurante_reservas/Controllers/ReservasController.cs
using restaurante_reservas.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace restaurante_reservas.Controllers
{
    public class ReservasController : Controller
    {
        // GET: Reservas
        restauranteEntities db = new restauranteEntities();
        public ActionResult AdminReservas()
        {
            try
            {
                var reservas = db.sp_Selecionar_Todas_Reservas().ToList();
                return View(reservas);
            }
            catch (Exception ex)
            {
                ViewData["Error"] = "Ocurrio un error : " + ex.Message;
                return View();
            }
        }

        // GET: Reservas/Details/5
        public ActionResult Details(int id)
        {
            sp_Selecionar_Todas_Reservas_Result myReserva = (from c in db.sp_Selecionar_Todas_Reservas() where id == c.id select c).First();
            return View(myReserva);

        }

        // GET: Reservas/Create
        public ActionResult Create()
        {
            List<Clientes> clientesList = db.Clientes.ToList();
            ViewBag.clientesList = new SelectList(clientesList, "id", "Cedula");
            return View();
        }

        // POST: Reservas/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                db.sp_Inserta_Reserva_Admin(Convert.ToDateTime(collection["fecha"]),Convert.ToInt32(collection["id_Cliente"]),5,Convert.ToInt32(collection["cantidad_personas"]));

                return RedirectToAction("AdminReservas");
            }
            catch(Exception ex)
            {
                ViewData["Error"] = "Ocurrio un error : " + ex.Message;
                return View();
            }
        }

        // GET: Reservas/Edit/5
        public ActionResult Edit(int id)
        {
            List<Estados> estadoList = db.Estados.Where(x => x.categoria == "reservas").ToList();
            ViewBag.estadoList = new SelectList(estadoList, "id", "estado");

            sp_Selecionar_Todas_Reservas_Result myReserva = (from c in db.sp_Selecionar_Todas_Reservas() where id == c.id select c ).First();
            return View(myReserva);
        }

        // POST: Reservas/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
                db.sp_Actualizar_Reserva(id, Convert.ToDateTime(collection["fecha"]),Convert.ToInt32(collection["id_Estado"]), Convert.ToInt32(collection["cantidad_personas"]));
                return RedirectToAction("AdminReservas");
            }
            catch(Exception ex)
            {
                ViewData["Error"] = "Ocurrio un error : " + ex.Message;
                return View();

            }
        }

        // GET: Reservas/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Reservas/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

restaurante_reservas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Restaurante</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
           

            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Menu", "Menu", "Home")</li>


                    @if (Session["clientelog"] != null)
                    {

                        if ((int)Session["clientelogRol"] != 1)
                        {
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person" viewBox="0 0 16 16">
                                        <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6Zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0Zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4Zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10Z" />
                                    </svg>Administrar<span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a href="@Url.Action("AdminClientes", "Clientes")">Clientes</a></li>
                                    <li><a href="@Url.Action("AdminReservas", "Reservas")">Reservas</a></li>
                                    <li><a href="@Url.Action("AdminMenu", "Home")">Menu</a></li>
                                    <li><a href="@Url.Action("LogOut", "Home")">Salir</a></li>
                                </ul>
                            </li>
                        }
                        else
                        {
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person" viewBox="0 0 16 16">
                                        <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6Zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0Zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4Zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10Z" />
                                    </svg>@Session["clientelognombre"] @Session["clientelogapellido1"] @Session["clientelogapellido2"]<span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a href="@Url.Action("ClienteInfo", "Home")">Mi Cuenta</a></li>
                                    <li><a href="@Url.Action("ClienteReservas", "Home")">Mis Reservas</a></li>
                                    <li><a href="@Url.Action("LogOut", "Home")">Salir</a></li>
                                </ul>
                            </li>
                        }
                    }
                    else
                    {
                        <li>@Html.ActionLink("Login", "Login", "Login")</li>
                    }
                </ul>
                <a href="@Url.Action("Reserva", "Home")" class="btn btn-success btn-sm" role="button" style="margin-top: 10px; float:right">Reservar</a>
            </div>
        </div>
    </div>
    <div class="container-fluid body-content" style="padding:0px !important; width:fit-content; height: min-content">
        @RenderBody()
    </div>

    <div class="navbar navbar-inverse navbar-fixed-bottom">
        <p style=" color: white; padding-left: 15px; padding-right: 15px; text-align:end">&copy; @DateTime.Now.Year - DHJ Technology</p>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>